apiVersion: v1
kind: ConfigMap
metadata:
  name: airflow-test-dag
  labels:
    app: airflow-test-dag
data:
  echo_test_dag.py: |
    from datetime import timedelta
    from airflow import DAG
    from airflow.operators.bash_operator import BashOperator
    from airflow.operators.python_operator import PythonOperator
    from airflow.utils.dates import days_ago
    from airflow import models, settings


    default_args = {
        "owner": "hyulee",
        "depends_on_past": True,
        "wait_for_downstream": True,
        "start_date": days_ago(0),
        "email": ["hyunseung@neosapience.com"],
        "email_on_failure": False,
        "email_on_retry": False,
    }

    dag = DAG(
        dag_id="echo_test_dag",
        default_args=default_args,
        description="테스트 DAG",
        schedule_interval=None,
    )
    dag.doc_md = __doc__

    task1 = BashOperator(
        task_id="task1",
        bash_command="date",
        dag=dag,
    )
    task1.doc_md = "### 테스트 Task ![img](http://montcs.bloomu.edu/~bobmon/Semesters/2012-01/491/import%20soul.png)"

    task2 = BashOperator(
        task_id="task2",
        bash_command="""
            {% for i in range(5) %}
                echo "{{ ds }}"
                echo "{{ macros.ds_add(ds, 7)}}"
                echo "{{ params.my_param }}"
            {% endfor %}
            """,
        params={"my_param": "Parameter I passed in"},
        dag=dag,
    )

    task1 >> task2
