apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow2-dp-flower
  labels:
    app: airflow2-flower
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow2-flower
  template:
    metadata:
      labels:
        app: airflow2-flower
    spec:
      containers:
      - name: airflow2-flower
        image: apache/airflow:2.8.2-python3.11
        args: ["celery", "flower"]
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 200m
            memory: 1Gi
        envFrom:
        - configMapRef:
            name: airflow-configmap