apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow2-dp-scheduler
  labels:
    app: airflow2-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow2-scheduler
  template:
    metadata:
      labels:
        app: airflow2-scheduler
    spec:
      containers:
      - name: airflow2-scheduler
        image: apache/airflow:2.2.2
        args: ["scheduler"]
        resources:
          requests:
            cpu: 500m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 1Gi
        envFrom:
        - configMapRef:
            name: airflow-configmap
        volumeMounts:
        - name: airflow-pvc-log
          mountPath: /home/airflow/logs
          readOnly: false
        - name: airflow-pvc-dag
          mountPath: /home/dags
          readOnly: false
      volumes:
      - name: airflow-pvc-dag
        persistentVolumeClaim:
          claimName: airflow-pvc-dag
      - name: airflow-pvc-log
        persistentVolumeClaim:
          claimName: airflow-pvc-log
