apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-dp-scheduler
  labels:
    app: airflow-scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-scheduler
  template:
    metadata:
      labels:
        app: airflow-scheduler
    spec:
      containers:
      - name: airflow-scheduler
        image: apache/airflow:2.2.2
        args: ["scheduler"]
        envFrom:
        - configMapRef:
            name: airflow-configmap

