apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow-dp-webserver
  labels:
    app: airflow-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow-webserver
  template:
    metadata:
      labels:
        app: airflow-webserver
    spec:
      containers:
      - name: airflow-webserver
        image: apache/airflow:2.2.2
        args: ["webserver"]
        envFrom:
        - configMapRef:
            name: airflow-configmap
        volumeMounts:
        - name: airflow-test-dag
          mountPath: /opt/airflow/dags/echo_test_dag.py
          subPath: echo_test_dag.py
      volumes:
      - name: airflow-test-dag
        configMap:
          name: airflow-test-dag

