apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow2-dp-webserver
  labels:
    app: airflow2-webserver
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow2-webserver
  template:
    metadata:
      labels:
        app: airflow2-webserver
    spec:
      containers:
      - name: airflow2-webserver
        image: apache/airflow:2.8.2-python3.11
        args: ["webserver"]
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        livenessProbe:
          exec:
            command:
              - cat
              - /home/airflow/airflow-webserver.pid
          initialDelaySeconds: 5
          periodSeconds: 30
          timeoutSeconds: 10
          successThreshold: 1
          failureThreshold: 3
        envFrom:
        - configMapRef:
            name: airflow-configmap
        volumeMounts:
        - name: airflow-pvc-log
          mountPath: /home/airflow/logs
          readOnly: false
        - name: airflow-pvc-dag
          mountPath: /home/airflow/dags
          readOnly: false
      volumes:
      - name: airflow-pvc-dag
        persistentVolumeClaim:
          claimName: airflow-pvc-dag
      - name: airflow-pvc-log
        persistentVolumeClaim:
          claimName: airflow-pvc-log
