apiVersion: apps/v1
kind: Deployment
metadata:
  name: airflow2-dp-worker
  labels:
    app: airflow2-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: airflow2-worker
  template:
    metadata:
      labels:
        app: airflow2-worker
    spec:
      serviceAccount: airflow2-sa
      containers:
      - name: airflow2-worker
        image: apache/airflow:2.8.2-python3.11
        args: ["celery", "worker"]
        resources:
          requests:
            cpu: 1000m
            memory: 2Gi
          limits:
            cpu: 1000m
            memory: 2Gi
        envFrom:
        - configMapRef:
            name: airflow-configmap
        volumeMounts:
        - name: aws-credential
          mountPath: {AWS_SECRET_PATH}
          readOnly: true
        - name: airflow-secret-google-test
          mountPath: {GOOGLE_SECRET_PATH}
          readOnly: true
        - name: airflow-pvc-log
          mountPath: /home/airflow/logs
          readOnly: false
        - name: airflow-pvc-dag
          mountPath: /home/airflow/dags
          readOnly: false
      volumes:
      - name: aws-credential
        secret:
          secretName: aws-k8s-userspace
          defaultMode: 0644
      - name: airflow-secret-google
        secret:
          secretName: airflow-secret-google
          defaultMode: 0644
      - name: airflow-pvc-dag
        persistentVolumeClaim:
          claimName: airflow-pvc-dag
      - name: airflow-pvc-log
        persistentVolumeClaim:
          claimName: airflow-pvc-log