apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - airflow_test_dag.yaml
  - dp-webserver.yaml
  - dp-scheduler.yaml
  - dp-worker.yaml
  - svc-webserver.yaml

namespace: airflow2

configMapGenerator:
  - name: airflow-configmap
    envs:
      - configmap.env
