apiVersion: v1
kind: Service
metadata:
  name: airflow-svc-flower
spec:
  type: ClusterIP
  selector:
    app: airflow-flower
  ports:
    - name: flower-port
      protocol: TCP
      port: 5555
      targetPort: 5555