apiVersion: v1
kind: Service
metadata:
  name: airflow2-svc-webserver
spec:
  type: ClusterIP
  selector:
    app: airflow2-webserver
  ports:
    - name: webserver-port
      protocol: TCP
      port: 8080
      targetPort: 8080